config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :events do
   # post :confirm, on: :collection
   resources :comments
   get :event_index, on: :member
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to:'top#index'
  # get '/users/eventrooms/:id', to: 'users#eventrooms'
  resources :users do
    member do
      get :followers, :following, :eventrooms, :event_index, :post_index, :favorites
    end
  end
  resources :eventrooms, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :labels
  # get 'search', to: 'events#search'
  resources :inquiries
  resources :conversations do
    resources :messages
  end
  resources :posts do
    resources :comments
    get :post_index, on: :member
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/authorize' => 'auth#gettoken'
  get '/feedbacks', to: 'feedbacks#new'
  post '/feedbacks', to: 'feedbacks#create'
  resources :feedbacks
  resources :notifications, only: :index
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :event, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="col-md-6.mx-auto">
  <div class="form-inline">
    <span><%= link_to user_path(visitor) do %>
            <%= image_tag visitor.icon_url(visitor).to_s, class: "icon_mini" %>
              <strong><%= visitor.name %></strong>
          <% end %>
          <%= 'さんが' %></span>

      <% case notification.action
      when 'follow' %>
        <%= 'あなたをフォローしました'%>
      <% when 'eventroom' %>
        <%= link_to 'あなたのイベント', notification.event, style: "font-weight: bold;" %>
        <%= 'に参加しました' %>
      <% when 'comment' %>
        <% if notification.event.user_id == visited.id %>
          <%= link_to "あなたの投稿", notification.event, style: "font-weight: bold;" %>
        <% else %>
          <span><%= link_to event_path(notification.event) do %>
                  <%= image_tag visitor.icon_url(notification.event.user).to_s, class: "icon_mini" %>
                  <strong><%= notification.event.user.name + "さんの投稿" %></strong>
                <% end %>
        <% end %>
        <%= "にコメントしました" %></span>
        <!-- <p class="text-muted.mb-0" ><%#= Comment.find_by(id: notification.comment_id)&.comment %></p> -->
      <% end %>
  </div>
</div>

app/views/notifications/index.html.erb
<%= render 'events_header' %>
<section class="page-section" id="about">
  <div class="container">
    <% notifications = @notifications.where.not(visitor_id: current_user.id)%>
    <% if notifications.exists?%>
      <%= render notifications %>
      <%= paginate notifications, class: "pagination" %>
    <% else %>
      <p>通知はありません</p>
    <% end %>
  </div>
</section>