config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :events do
   # post :confirm, on: :collection
   resources :comments
   get :event_index, on: :member
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to:'top#index'
  # get '/users/eventrooms/:id', to: 'users#eventrooms'
  resources :users do
    member do
      get :followers, :following, :eventrooms, :event_index, :post_index, :favorites
    end
  end
  resources :eventrooms, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :labels
  # get 'search', to: 'events#search'
  resources :inquiries
  resources :conversations do
    resources :messages
  end
  resources :posts do
    resources :comments
    get :post_index, on: :member
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/authorize' => 'auth#gettoken'
  get '/feedbacks', to: 'feedbacks#new'
  post '/feedbacks', to: 'feedbacks#create'
  resources :feedbacks
  resources :notifications, only: :index
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { in: 1..255 }
  validates :content, presence: true, length: { in: 1..900 }
  # validates :fee, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validate :fee_validate
  validates :place, presence: true, length: { in: 1..100 }
  validate :date_before_today, on: :create
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :eventrooms, dependent: :destroy
  has_many :eventroom_users, through: :eventrooms, source: :user
  has_many :comments, dependent: :destroy
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings, source: :label
  has_many :notifications, dependent: :destroy

  def date_before_today
    errors.add(:event_date, "は本日以降のものを選択してください") if event_date.nil? || event_date < DateTime.now
  end

  scope :created_after, -> (time) {
  time = time.to_time
  where('event_date > ?', time)
  }
  scope :created_before, -> (time) {
  time = time.to_time
  where('event_date < ?', time)
  }

  class << self
    def ransackable_scopes(auth_object = nil)
      [:created_after, :created_before]
    end
  end

  def fee_validate
    errors.add(:fee, "は0より大きくなければなりません。") if fee.nil? || fee < 0
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and event_id = ? and action = ? ", current_user.id, user_id, id, 'eventroom'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        event_id: id,
        visited_id: user_id,
        action: 'eventroom'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(event_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      event_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :event_index]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :check_event, only: [:edit, :update, :destroy]

  def index
    search_options = {
      created_after: params[:created_after],
      created_before: params[:created_before]
      }
    @q = Event.ransack(params[:q], search_options)
    @events = @q.result(distinct: true).includes(:labelings, :labels).order(event_date: :asc).where('event_date > ?', DateTime.now).page(params[:page]).per(10)
    # @events = @events.where('event_date > ?', DateTime.now).order(event_date: :asc)
    # @events = @events.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
  end

  def show
    @comments = @event.comments
    @comment = @event.comments.build
    if user_signed_in?
     @eventroom = current_user.eventrooms.find_by(event_id: @event.id)
    end
    @eventrooms = Eventroom.where(event_id: @event.id)
    @user = @event.user
  end
  def event_index
  end

  def new
    @event = Event.new
  end

  def edit
  end

  # def confirm
  #  @event = current_user.events.build(event_params)
  #  render :new if @event.invalid?
  # end

  def create
    @event = current_user.events.build(event_params)
    if params[:back]
      render :new
    else
       if @event.save
         # eventMailer.contact_mail(@event).deliver
         redirect_to events_path, notice: t('notice.create')
       else
         render :new
       end
    end
  end

  def update
    if params[:back]
      render :edit
    else
      if @event.update(event_params)
        redirect_to events_path, notice: t('notice.update')
      else
        render :edit
      end
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: t('notice.destroy')
  end

 private
 def set_event
   @event = Event.find(params[:id])
 end

 def event_params
   params.require(:event).permit(:image, :image_cache, :remove_image, :id, :content, :title, :event_date, :place, :fee, :contact, :owner_id, {
     label_ids:[]
     })
 end
 def check_event
   unless current_user.try(:admin)
     if current_user.id != @event.user.id
       redirect_to events_path, notice: '権限がありません'
     end
   end
 end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> 作成できません</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>
  <div class="form-group">
        <%= form_with(model: @event, local: true) do |f| %>
          <%= image_tag @event.image.url  if @event.image && @event.image.url %>
          <%= f.label :image ,class:'sr-only btn btn-primary'%>
          <%= f.hidden_field :image_cache %>
          <%= f.file_field :image , class: "form-control-file"%>
          <p><%= f.check_box :remove_image %>画像を削除</p>
          <div class=”input-group” >
          <%= f.label :title ,class:'sr-only'%>
          <%= f.text_field :title ,placeholder:"タイトル",class: "form-control form-control"%>
          </div>
          <div class=”input-group”>
          <%= f.label :content ,class:'sr-only'%>
          <%= f.text_area :content ,class:"form-control", placeholder:"詳細" %>
          </div>
          <div class="input-group">
          <%= f.label :event_date %>
          <%= f.datetime_select :event_date, include_blank: true, minute_step: 10 ,class: "form-control form-control"%>
          </div>
          <div class=”input-group” >
          <%= f.label :place %>
          <%= f.text_field :place, placeholder: "例：オンライン、東京都渋谷区" ,class: "form-control form-control"%>
          </div>
          <div class=”input-group” >
          <%= f.label :fee %>
          <%= f.number_field :fee, placeholder: "無料の場合は0",class: "form-control form-control" %>
          </div>
          <div class=”input-group” >
          <%= f.label :contact %>
          <%= f.text_field :contact, placeholder: "zoomのurlなど" ,class: "form-control form-control"%>
          </div>
          <div class=”input-group” >
          <%= f.collection_check_boxes(:label_ids, Label.all, :id, :name, class: "form-check-input") %>
          </div>
        <div class="actions">
          <%= f.submit "投稿する",class: 'btn btn-primary'%>
        </div>
      <% end %>
  </div>

app/views/events/confirm.html.erb
<%= render 'events_header' %>
<section class="page-section" id="about">
  <div class="container">
    <h3>以下の内容で、投稿する。</h3>
      <%= form_with(model: @event, local: true) do |f| %>
        <%= image_tag(@event.image.url) if @event.image && @event.image.url %>
        <%= f.hidden_field :image_cache %>
        <%= f.hidden_field :title %>
        <%= f.hidden_field :content %>
        <%= f.hidden_field :event_date %>
        <%= f.hidden_field :place %>
        <%= f.hidden_field :fee %>
        <%= f.hidden_field :contact %>
        <p>タイトル:<%= @event.title %></p>
        <p>詳細:<%= @event.content %></p>
        <p>開催日時:<%= @event.event_date %></p>
        <p>場所:<%= @event.place %></p>
        <p>参加費:<%= @event.fee %></p>
        <p>連絡事項:<%= @event.contact %></p>
        <%= f.submit  "作成する" %>
      <% end %>
      <%= form_with(model:@event, url:events_path, local:true, method:"get") do |f| %>
        <%= f.hidden_field :image_cache %>
        <%= f.submit "戻る", name: "back" %>
      <% end %>
  </div>
</section>

app/views/events/edit.html.erb
<%= render 'user_header' %>
<section class="page-section" id="about">
  <div class="container">
    <%= render 'form', event: @event %>
    <%= link_to 'Show', @event %> |
    <%= link_to 'Back', events_path %>
  </div>
</section>

app/views/events/index.html.erb
<%= render 'events_header' %>
<header class="masthead_event">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">More Beautiful Now</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
              <%= search_form_for @q do |f| %>
                <%= f.search_field :title_or_content_cont, {placeholder: "タイトルから検索",class: "form-group form-control search_title" } %>
                <%= f.select :labels_name_cont, options_from_collection_for_select(Label.all, :name, :name, "---") ,include_blank: '選択',class: 'form-control drop search_label' %>
                <p><%= f.date_field :created_after %></p>
                <p><%= f.date_field :created_before %></p>
                <%= f.submit "検索" ,class: "btn btn-outline-light search-event-secondary"%>
                <%= link_to '検索条件クリア', request.path ,class: "btn btn-outline-primary search-event-primary"%>
              <% end %>
            </div>
        </div>
    </div>
</header>
<section class="page-section" id="about">
  <div class="container">
    <!-- 一覧 -->
    <div class="container-fluid">
      <div class="row h-100 align-items-center justify-content-center">
        <div class="col-lg-10 align-self-end">
          <% @events.each do |event| %>
            <div class="card">
              <div class="card-header">
                <%= l event.event_date %>
              </div>
              <div class="card-body">
                <%= image_tag event.image.url, size: "200x150",class: "float-left" %>
                <h5 class="card-title"><%= link_to event.title, event %></h5>
                <p class="card-text">主催者：<%= event.user.name %></p>
                <p class="card-text">開催場所：<%= event.place %></p>
                <p><% event.labels.each do |label| %><label class='badge badge-primary'><%= label.name %></label><% end %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<div>
  <%= paginate @events ,class:"pagination" %>
</div>

app/views/events/new.html.erb
<%= render 'events_header' %>
<section class="page-section" id="about">
  <div class="container">
    <h3>新規投稿</h3>
    <%= render 'form', event: @event %>
    <%= link_to 'Back', events_path %>
  </div>
</section>

app/views/events/show.html.erb
<%= render 'events_header' %>
<section class="page-section" id="about">
  <div class="container">
    <!-- 編集削除ボタン -->
    <div class="text-right">
      <% if user_signed_in? && current_user.id == @event.user_id || current_user.try(:admin?)%>
        <%= link_to 'Edit', edit_event_path(@event) %> |
        <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% end %>
        <%= link_to 'Back', events_path %>
        <br>
    </div>
    <br>
    <!-- 詳細内容-->
    <div class="container-fluid">
      <div class="base-event-view-content">
        <div id="visual-banner">
          <div id="visual-banner-preview">
            <%= image_tag @event.image.url, class: "event_image"%>
          </div>
        </div>
        <hgroup>
          <div id="field-event-name" ><h1 class="event-name-ttl"><%= @event.title %></h1></div>
          <div class="subtitle-box">
            <div id="field-event-subtitle" >
            <strong></strong>
            </div>
          </div>
        </hgroup>
        <!-- メイン-->
        <div class="row">
          <div class="col-sm-8">
            <div class="box-wide">
              <div class="event">
                <span class="tags">詳細</span>
                <div id="field-event-description" class="event-description">
                  <section><%= safe_join(@event.content.split("\n"),tag(:br)) %></section>
                </div>
              </div>
            </div>
            <div class="event-section">
              <div class="tag-list">
                <% @event.labels.each do |label| %><label class='badge badge-primary'><%= label.name %></label><% end %>
              </div>
            </div>
            <div class="event-section">
              <div class="tag-list">
                <% if user_signed_in? && @eventroom.present? || @user == current_user %>
                  <p>連絡事項：<%= @event.contact %></p>
                <% end %>
              </div>
            </div>
            <div class="event-section">
              <div class="tag-list">
                <div id="comments_area">
                  <% if user_signed_in? %>
                    <%= render partial: 'comments/index', locals: { comments: @comments, event: @event } %>
                  <% end %>
                </div>
                  <% if user_signed_in? %>
                    <%= render partial: 'comments/form', locals: { comment: @comment, event: @event } %>
                  <% end %>
              </div>
            </div>
          </div>
          <!-- サブ-->
          <div class="col-sm-4">
            <div class="tix-box">
              <div class="tix-box-content">
                <div class="tix-detail cf">
                  <strong><%= l @event.event_date %></strong>
                </div>
              </div>
            </div>
            <dl class="tix-detail cf">
              <dt>会場</dt>
              <dd><%= @event.place %></dd>
            </dl>
             <dl class="tix-detail tickets tix-detail-wide cf" id="tickets-section">
               <dt class="cf">参加費</dt>
               <dd>
                 <table class="tix-types">
                   <tr id="tix-1995560" class="js-ticket-section">
                     <td class="price"><%= @event.fee %>円</td>
                    </tr>
                  </table>
                </dd>
              </dl>
            <div class="tix-detail tix-action">
              <% if user_signed_in? && current_user.id != @event.user_id %>
                <% if @eventroom.present? %>
                  <p><%= link_to 'イベントをキャンセル', eventroom_path(id: @eventroom.id), method: :delete ,class: 'btn btn-primary' %></p>
                <% else %>
                  <p><%= link_to 'イベントに参加する', eventrooms_path(event_id: @event.id), method: :post ,class: 'btn btn-primary' %></p>
                <% end %>
              <% end %>
            </div>
            <dl class="tix-detail tix-detail-wide tix-detail__organizer">
              <dt>主催者</dt>
              <dd class="tix-organizer-name">
                <%= link_to @event.user.name, user_path(@event.user.id) %>
              </dd>
            </dl>
            <div class="attendees">
              <strong class="tags">参加者</strong>
              <% if user_signed_in? %>
                <% @eventrooms.each do |eventroom| %>
                  <ul class="attendee-list" style="margin-top:20px">
                    <li class="cf"> <%= link_to eventroom.user.name, user_path(eventroom.user_id) %><%= image_tag eventroom.user.icon.url, size: "40x40" %></li>
                  </ul>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>



  </div>
</section>