config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :events do
   # post :confirm, on: :collection
   resources :comments
   get :event_index, on: :member
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to:'top#index'
  # get '/users/eventrooms/:id', to: 'users#eventrooms'
  resources :users do
    member do
      get :followers, :following, :eventrooms, :event_index, :post_index, :favorites
    end
  end
  resources :eventrooms, only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :labels
  # get 'search', to: 'events#search'
  resources :inquiries
  resources :conversations do
    resources :messages
  end
  resources :posts do
    resources :comments
    get :post_index, on: :member
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/authorize' => 'auth#gettoken'
  get '/feedbacks', to: 'feedbacks#new'
  post '/feedbacks', to: 'feedbacks#create'
  resources :feedbacks
  resources :notifications, only: :index
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { in: 1..255 }
  validates :content, presence: true, length: { in: 1..900 }
  validates :cosmetic, presence: true, length: { in: 1..900 }
  has_many :postlabelings, dependent: :destroy
  has_many :labels, through: :postlabelings, source: :label

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :likes
  has_many :likes_users, through: :likes, source: :user

  mount_uploader :image, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :event_index]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :check_post, only: [:edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:postlabelings, :labels).order(created_at: :desc).page(params[:page]).per(10)
    # @events = @events.where('event_date > ?', DateTime.now).order(event_date: :asc)
    # @events = @events.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
  end

  def show
    # @comments = @event.comments
    # @comment = @event.comments.build
    if user_signed_in?
      @favorite = current_user.favorites.find_by(post_id: @post.id)
      @like = current_user.likes.find_by(post_id: @post.id)
     end
     @favorites = Favorite.where(post_id: @post.id)
     @likes = Like.where(post_id: @post.id)
  end
  def post_index
  end

  def new
    @post = Post.new
  end

  def edit
  end

  # def confirm
  #  @event = current_user.events.build(event_params)
  #  render :new if @event.invalid?
  # end

  def create
    @post = current_user.posts.build(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if params[:back]
      render :new
    else
       if @post.save
         # eventMailer.contact_mail(@event).deliver
         redirect_to posts_path, notice: t('notice.create')
       else
         render :new
       end
    end
  end

  def update
    if params[:back]
      render :edit
    else
      if @post.update(post_params)
        redirect_to posts_path, notice: t('notice.update')
      else
        render :edit
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: t('notice.destroy')
  end

 private
 def set_post
   @post= Post.find(params[:id])
 end

 def post_params
   params.require(:post).permit(:image, :image_cache, :remove_image, :id, :content, :title, :cosmetic, :youtube_url,
     {label_ids:[]})
 end
 def check_post
   unless current_user.try(:admin)
     if current_user.id != @post.user.id
       redirect_to posts_path, notice: '権限がありません'
     end
   end
 end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> 作成できません</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>
  <div class="form-group">
        <%= form_with(model: @post, local: true) do |f| %>
          <%= image_tag @post.image.url  if @post.image && @post.image.url %>
          <%= f.label :image ,class:'sr-only btn btn-primary'%>
          <%= f.hidden_field :image_cache %>
          <%= f.file_field :image , class: "form-control-file"%>
          <p><%= f.check_box :remove_image %>画像を削除</p>
          <div class=”input-group” >
          <%= f.label :title ,class:'sr-only'%>
          <%= f.text_field :title ,placeholder:"タイトル",class: "form-control form-control"%>
          </div>
          <div class=”input-group”>
          <%= f.label :content ,class:'sr-only'%>
          <%= f.text_area :content ,class:"form-control", placeholder:"詳細" %>
          </div>
          <div class=”input-group”>
          <%= f.label :cosmetic ,class:'sr-only'%>
          <%= f.text_area :cosmetic ,class:"form-control", placeholder:"使用コスメ" %>
          </div>
          <div class=”input-group” >
          <%= f.label :youtube_url ,class:'sr-only'%>
          <%= f.text_field :youtube_url ,placeholder:"youtubeurl",class: "form-control form-control"%>
          </div>
          <div class=”input-group” >
          <%= f.collection_check_boxes(:label_ids, Label.all, :id, :name, class: "form-check-input") %>
          </div>
        <div class="actions">
          <%= f.submit "投稿する",class: 'btn btn-primary'%>
        </div>
      <% end %>
  </div>

app/views/posts/edit.html.erb
<%= render 'user_header' %>
<section class="page-section" id="about">
  <div class="container">
    <%= render 'form', post: @post %>
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
  </div>
</section>

app/views/posts/index.html.erb
<%= render 'events_header' %>
<header class="masthead_post">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">More Beautiful Now</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
              <%= search_form_for @q do |f| %>
                <%= f.search_field :title_or_content_cont, {placeholder: "タイトルから検索",class: "form-group form-control search_title" } %>
                <%= f.select :labels_name_cont, options_from_collection_for_select(Label.all, :name, :name, "---") ,include_blank: '選択',class: 'form-control drop search_label' %>
                <%= f.submit "検索" ,class: "btn btn-outline-light search-event-secondary"%>
                <%= link_to '検索条件クリア', request.path ,class: "btn btn-outline-primary search-event-primary"%>
              <% end %>
            </div>
        </div>
    </div>
</header>
<section class="page-section" id="about">
  <div class="container">
    <!-- 一覧 -->
    <div class="container-fluid">
      <div class="row h-100 align-items-center justify-content-center">
        <div class="col-lg-10 align-self-end">
          <% @posts.each do |post| %>
            <div class="card">
              <div class="card-header">
                <%= post.title %>
              </div>
              <div class="card-body">
                <%= image_tag post.image.url, size: "200x150",class: "float-left" %>
                <h5 class="card-title"><%= link_to post.title, post %></h5>
                <p class="card-text"><%= post.user.name %></p>
                <p><% post.labels.each do |label| %><label class='badge badge-primary'><%= label.name %></label><% end %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<div>
  <%= paginate @posts ,class:"pagination" %>
</div>

app/views/posts/new.html.erb
<%= render 'events_header' %>
<section class="page-section" id="about">
  <div class="container">
    <h3>新規投稿</h3>
    <%= render 'form', post: @post %>
    <%= link_to 'Back', posts_path %>
  </div>
</section>

app/views/posts/show.html.erb
<%= render 'events_header' %>
<section class="page-section" id="about">
  <div class="container">
    <!-- 編集削除ボタン -->
    <div class="text-right">
      <% if user_signed_in? && current_user.id == @post.user_id || current_user.try(:admin?)%>
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% end %>
        <%= link_to 'Back', posts_path %>
    </div>
    <br>
    <!-- お気に入り-->
    <div class="tix-detail tix-action">
      <% if user_signed_in? && current_user.id != @post.user_id %>
        <% if @favorite.present? %>
          <p><%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete ,class: 'btn btn-primary' %></p>
        <% else %>
          <p><%= link_to 'お気に入りする', favorites_path(post_id: @post.id), method: :post ,class: 'btn btn-primary' %></p>
        <% end %>
      <% end %>
    </div>
    <!-- いいね-->
    <div class="tix-detail tix-action">
      <% if user_signed_in? && current_user.id != @post.user_id %>
        <% if @like.present? %>
          <%= link_to like_path(id: @like.id), method: :delete do %>
            <i class="fas fa-heart unlike-btn"></i>
          <% end %>
        <% else %>
          <%= link_to likes_path(post_id: @post.id), method: :post do %>
            <i class="far fa-heart like-btn" ></i>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <!-- 詳細内容-->
    <div class="base base-event-view">
      <div class="base-event-view-content">
        <div id="visual-banner">
          <div id="visual-banner-preview">
            <%= image_tag @post.image.url, class: "post_image"%>
          </div>
        </div>
        <hgroup>
          <div id="field-event-name" ><h1 class="event-name-ttl"><%= @post.title %></h1></div>
          <div class="subtitle-box">
            <div id="field-event-subtitle" >
            <strong></strong>
            </div>
          </div>
        </hgroup>
        <div class="col-main">
          <div class="box-wide">
            <div class="post">
              <span class="tags">投稿者</span>
              <div id="field-event-description" class="event-description">
                <section><%= link_to @post.user.name, user_path(@post.user.id) %></section>
              </div>
            </div>
            <div class="post">
              <span class="tags">詳細</span>
              <div id="field-event-description" class="event-description">
                <section><%= safe_join(@post.content.split("\n"),tag(:br)) %></section>
              </div>
            </div>
            <div class="post">
              <span class="tags">メイク道具</span>
              <div id="field-event-description" class="event-description">
                <section><%= safe_join(@post.cosmetic.split("\n"),tag(:br)) %></section>
              </div>
            </div>
            <div class="post center-block"">
              <% if @post.youtube_url.present? %>
              <span class="tags">youtube</span>
              <div id="field-event-description" class="event-description">
                <section><iframe width="890" height="400" src="https://www.youtube.com/embed/<%= @post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></section>
              </div>
              <% end %>
            </div>
          </div>
          <div class="post-section">
            <div class="tag-list">
              <% @post.labels.each do |label| %><label class='badge badge-primary'><%= label.name %></label><% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>